##
- name: Initialize an empty list to store datasources
  ansible.builtin.set_fact:
    datasources: []
  delegate_to: localhost
  run_once: true

- name: Reset page size and page number
  ansible.builtin.set_fact:
    pageSize: 1000
    pageNumber: 1
    has_more_pages: true

- name: List datasources
  ansible.builtin.uri:
    url: "https://{{ TableadatasourceverName }}/api/{{ Tableau_API_Version }}/sites/{{ Tableau_Site_ID }}/datasources?pageSize={{ pageSize }}&pageNumber={{ pageNumber }}"
    method: GET
    headers:
      Content-Type: application/json
      Accept: application/json
      X-Tableau-Auth: "{{ hostvars['localhost'].Tableau_Authentication_Token }}"
    validate_certs: false
    return_content: true
    use_proxy: false
    follow_redirects: all
  register: datasources_response
  failed_when: datasources_response.status != 200
  until: datasources_response.json.datasources.datasource | length < pageSize
  retries: 5
  delay: 2
  when: Tableau_Authentication_Token is defined

- name: Append datasources to the list
  ansible.builtin.set_fact:
    datasources: "{{ datasources + (datasources_response.json.datasources.datasource  | default([])) }}"
    pageNumber: "{{ pageNumber + 1 }}"
  delegate_to: localhost
  run_once: true
  when: datasources_response.json.datasources.datasource | length > 0
  # when: datasources_response.json.datasources.datasource | length > 0 and datasources_response.json.datasources.datasource is defined 