
- name: RMT_Installation Verification
  block:
    - name: Verify Tableau RMT installation in server log. This task uses a windows Find command.
      ansible.windows.win_shell: |
        find "Installation completed successfully" "Tableau_Resource_Monitoring_Tool_*Server.log"
      args: 
        executable: cmd
        chdir: "{{ C:\\Users\\{{ hostvars['localhost'].CyberArk_UserName }}\\AppData\\Local\\Temp\\}}"
      register: RMT_Installation

    - name: Verify Tableau RMT installation in server log. This task uses a windows PowerShell Select-String Function.
      ansible.windows.win_shell: |
        Select-String -Path "Tableau_Resource_Monitoring_Tool_*Server.log" -Pattern 'Installation completed successfully' | sort LastWriteTime | select -last 1
      args: 
        executable: PowerShell
        chdir: "{{ C:\\Users\\{{ hostvars['localhost'].CyberArk_UserName }}\\AppData\\Local\\Temp\\}}"
      register: RMT_Installation
