##
- name: Set Project Permissions
  ansible.builtin.uri:
    url: "https://{{ TableauServerName }}/api/{{ Tableau_API_Version }}/sites/{{ Tableau_Site_ID }}/projects/{{ Project_ID }}/permissions"
    method: PUT
    headers:
      Content-Type: application/json
      Accept: application/json
      X-Tableau-Auth: "{{ hostvars['localhost'].Tableau_Authentication_Token }}"
    body: |
      {
        "permissions": {
          "granteeCapabilities": [
            {
              "capabilities": {
                "capability": [ 
                  { "mode": "Allow" ,
                    "name": "Read"
                  },
                  { "mode": "Allow" ,
                    "name": "Write"
                  }
                ]
              },
              "group": {
                "id": "{{ group_id }}"
              }
            }
          ]
        }
      }
    body_format: json
    validate_certs: false
    return_content: true
    use_proxy: false
    follow_redirects: all
  register: set_project_permissions_response
  failed_when: set_project_permissions_response.status != 200
  changed_when: set_project_permissions_response.status != 200
  until: set_project_permissions_response.status == 200
  retries: 3
  delay: 5
  when: set_project_permissions_response is not defined or set_project_permissions_response.status != 200
  