

- name: Task | Get CyberArk Password
  cyberark.pas.cyberark_credential:
    api_base_url: "{{ CyberArk_API_Base_URL }}"
    validate_certs: false
    client_cert: "{{ CyberArk_Cert }}"
    client_key: "{{ CyberArk_Key }}"
    app_id: "{{ CyberArk_App_ID }}"
    query: "{{ CyberArk_Query }}"
    connection_timeout: 15
    query_format: Exact
    reason: "Service Account - Requesting Credential for Ansible Automation."
  no_log: false
  register: CyberArk_Result

- name: Debug CyberArk_Result
  debug:
    var: CyberArk_Result.result
  no_log: false

  
