
- name: Select CyberArk Account
  ansible.builtin.set_fact:
    CyberArk_App_ID: "{{ item.accounts | selectattr('account_name','equalto',targeted_cyberark_account_name) | map(attribute='App_ID') | first }}"
    CyberArk_Safe: "{{ item.accounts | selectattr('account_name','equalto',targeted_cyberark_account_name) | map(attribute='Safe') | first }}"
    CyberArk_Object: "{{ item.accounts | selectattr('account_name','equalto',targeted_cyberark_account_name) | map(attribute='object') | first}}"
  loop: "{{ CyberArk_Accounts | selectattr('environment','equalto',targeted_environment) }}"
  delegate_to: localhost
  run_once: true

# | regex_replace(' ', '%20' - This regex expression will remove the space(s) in the URL.
- name: Task | Get CyberArk Password
  ansible.builtin.url::
    url: "{{ item.base_url }}AppID={{ item.CyberArk_App_ID }}&Safe={{ item.CyberArk_Safe }}&Object={{ item.CyberArk_Object }} | regex_replace(' ', '%20'"
    validate_certs: false
    client_cert: "{{ CyberArk_Cert }}"
    client_key: "{{ CyberArk_Key }}"
    headers:
      HTTP_VERSION: "HTTP/1.1" # this is used when there are older versions of HTTP installed on servers.
    return_content: true
  #loop: "{{ CyberArk_Accounts | selectattr('environment','equalto',targeted_environment) }}" # Can't remember if this needs another loop or not. Wrote this from memory. I will need to play with the set fact above that uses a loop to find out.
  no_log: false
  register: CyberArk_Result

- name: Debug CyberArk_Result
  debug:
    var: CyberArk_Result.result
  no_log: false

# hostvars['localhost'][variable] - This will set this fact to a Global Ansible Varriable for all hosts to use. 
- name: Set Fact CyberArk_Result UserName
  ansible.builtin.set_fact:
    CyberArk_UserName: "{{ hostvars['localhost'][item.json.UserName] }}" # This may need to be seperated before it can become a Global Varriable. Wrote this from memory.
    CyberArk_Password: "{{ hostvars['localhost'][item.json.Content] }}" # This may need to be seperated before it can become a Global Varriable. Wrote this from memory.
  loop: "{{ CyberArk_Result.results }}"
  delegate_to: localhost
  run_once: true
