##
- name: Initialize an empty list to store projects
  ansible.builtin.set_fact:
    projects: []
  delegate_to: localhost
  run_once: true

- name: Reset page size and page number
  ansible.builtin.set_fact:
    pageSize: 1000
    pageNumber: 1
    has_more_pages: true

- name: List projects
  ansible.builtin.uri:
    url: "https://{{ TableauServerName }}/api/{{ Tableau_API_Version }}/sites/{{ Tableau_Site_ID }}/projects?pageSize={{ pageSize }}&pageNumber={{ pageNumber }}"
    method: GET
    headers:
      Content-Type: application/json
      Accept: application/json
      X-Tableau-Auth: "{{ hostvars['localhost'].Tableau_Authentication_Token }}"
    validate_certs: false
    return_content: true
    use_proxy: false
    follow_redirects: all
  register: projects_response
  failed_when: projects_response.status != 200
  until: projects_response.json.projects.project | length < pageSize
  retries: 5
  delay: 2
  when: Tableau_Authentication_Token is defined

- name: Append projects to the list
  ansible.builtin.set_fact:
    projects: "{{ projects + (projects_response.json.projects.project  | default([])) }}"
    pageNumber: "{{ pageNumber + 1 }}"
  delegate_to: localhost
  run_once: true
  when: projects_response.json.projects.project | length > 0
  # when: projects_response.json.projects.project | length > 0 and projects_response.json.projects.project is defined 