- name: Get ALL of the Tableau Users for a Group.
  block:
    - name: Get ALL of the Tableau Users for a Group.
      ansible.builtin.url:
        url: "https://{{ TableauServerName }}/api/{{ Tableau_API_Version }}/sites/{{ Tableau_Site_ID }}/groups/{{ Tableau_Group_ID }}/users"
        method: GET
        headers: 
          Content-Type: application/json
          Accept: application/json
          X-Tableau-Auth: "{{ hostvars['localhost'].Tableau_Authentication_Token }}"
          #HTTP_VERSION: "HTTP1/1"
        #body: 
          #credentials:
            #username: "{{ hostvars['localhost'].CyberArk_UserName }}"
            #password: "{{ hostvars['localhost'].CyberArk_Password }}"
        #body_format: json
        validate_certs: false
        return_content: true
      register: Tableau_Users_Response
      failed_when: Tableau_Users_Response.status !=200

    - name: Set Ansible Fact Tableau Users Fact(s).
      ansible.builtin.set_fact:
        Tableau_Users: "{{ Tableau_Users_Response.json.users.group }}"
        Tableau_User_Info: "{{ Tableau_Users_Response.json.users.group | selectattr('name', 'search', 'Tableau-Company-User-Name' }}"
        Tableau_User_Name: "{{ (Tableau_Users_Response.json.users.group | selectattr('name', 'search', 'Tableau-Company-User-Name' | first).name }}"
        Tableau_User_ID: "{{ (Tableau_Users_Response.json.users.group | selectattr('name', 'search', 'Tableau-Company-User-Name' | first).id }}"
      delegate_to: localhost
      run_once: true

