
- name: Tableau Server Dynamic Topology.
  block:
    - name: Log into Tableu.
      win_shell: tsm login -s localhost -u {{ hostvars['localhost'].CyberArk_UserName }} -p "{{ hostvars['localhost'].CyberArk_Password }}"
      args:
        executable: cmd
        chdir: "C:\\Tableau"
      register: TSM_Login      

    - name: Tableu Dynamic Topology - Set the vizqlserver count.
      win_shell: tsm topology set-process --process vizqlserver --node "{{ Node_ID }}" --count "{{ vizqlserver_Count }}"
      args:
        executable: cmd
        chdir: "C:\\Tableau"
      register: TSM_vizqlserver

    - name: Tableu Dynamic Topology - Set the backgrounder count.
      win_shell: tsm topology set-process --process backgrounder --node "{{ Node_ID }}" --count "{{ backgrounder_Count }}"
      args:
        executable: cmd
        chdir: "C:\\Tableau"
      register: TSM_backgrounder      

  rescue:
    - name: RESCUE - TSM Pending Changes Discard - RESCUE
      win_shell: tsm pending-changes discard --ignore-prompt --ignore-warnings
      args:
        executable: cmd
        chdir: "C:\\Tableau"
      register: TSM_Pending_Changes_Discard

  always:
    - name: Verify Tableau is running.
      win_shell: tsm status
      args:
        executable: cmd
        chdir: "C:\\Tableau"
      register: TSM_Status
      ignore_errors: true
      failed_when: not TSM_Status.stdout is search(tableau_status_running) or TSM_Status.rc !=0
      changed_when: TSM_Status.stdout is search(tableau_status_running)
      until: TSM_Status.stdout is search(tableau_status_running) or TSM_Status.stdout is search(tableau_status_stopped)
      retries: 10
      delay: 5      

- name: Debug - TSM Status - End of Tableau Dynamic Topology.
  debug:
    msg: "Tableau Status is: {{ TSM_Status.stdout }}"

